<a href="https://colab.research.google.com/github/chaerui7967/stock_predict_news_and_youtube/blob/master/%EC%A0%84%EC%B2%B4%ED%86%B5%ED%95%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
import numpy as np

In [5]:
path = '/content/drive/My Drive/Final PJT - 업빛투/최종 결과 테이블/'

In [9]:
# 기본 테이블
samsung = pd.read_csv(path + '삼성전자/total_table.csv')
lg = pd.read_csv(path + 'lg화학/total_table.csv')
sk = pd.read_csv(path + 'sk하이닉스/total_table.csv')
hun = pd.read_csv(path + '현대차/total_table.csv')
cell = pd.read_csv(path + '셀트리온/total_table.csv')

total = pd.concat([samsung,lg,sk,hun,cell])
total

    code        date           lstm  ...  suka_youtube   close    change
0   5930  2021-09-15   75635.242676  ...      0.508731   77000       NaN
1   5930  2021-09-16   75637.329590  ...      0.508731   76100       NaN
2   5930  2021-09-17   76096.152832  ...      0.508731   77200       NaN
3   5930  2021-09-23   76369.526611  ...      0.508731   77400       NaN
4   5930  2021-09-24   76418.150635  ...      0.508731   77300       NaN
5   5930  2021-09-27   76359.406738  ...      0.508731   77700       NaN
6   5930  2021-09-28   76422.000000  ...      0.508731   76300       NaN
7   5930  2021-09-29   76854.091064  ...      0.508731   74100       NaN
8   5930  2021-09-30   76312.112305  ...      0.508731   74100       NaN
9   5930  2021-10-01   75350.940186  ...      0.508731   73200       NaN
0  51910  2021-09-15  733916.571140  ...      0.508730  718000 -0.021798
1  51910  2021-09-16  730745.079160  ...      0.508730  716000 -0.002786
2  51910  2021-09-17  727474.198222  ...      0.508730  701000 -0.020950
3  51910  2021-09-23  723239.910305  ...      0.508730  760000  0.084165
4  51910  2021-09-24  721332.248360  ...      0.508730  761000  0.001316
5  51910  2021-09-27  721468.415320  ...      0.508730  770000  0.011827
6  51910  2021-09-28  725266.111761  ...      0.508730  776000  0.007792
7  51910  2021-09-29  730308.284700  ...      0.508730  767000 -0.011598
8  51910  2021-09-30  732722.755849  ...      0.508730  776000  0.011734
9  51910  2021-10-01  736871.808171  ...      0.508730  770000 -0.007732
0    660  2021-09-15  107611.110840  ...      0.508730  107500  0.000000
1    660  2021-09-16  106315.300781  ...      0.508730  104000 -0.032558
2    660  2021-09-17  106507.104492  ...      0.508730  107000  0.028846
3    660  2021-09-23  105733.528809  ...      0.508730  105500 -0.014019
4    660  2021-09-24  105307.092773  ...      0.508730  104000 -0.014218
5    660  2021-09-27  105843.469727  ...      0.508730  104500  0.004808
6    660  2021-09-28  104409.901855  ...      0.508730  103500 -0.009569
7    660  2021-09-29  105048.020996  ...      0.508730  100000 -0.033816
8    660  2021-09-30  101771.489502  ...      0.508730  103000  0.030000
9    660  2021-10-01  101373.722412  ...      0.508730  100000 -0.029126
0   5380  2021-09-15  208400.868164  ...      0.508730  209500  0.002392
1   5380  2021-09-16  207487.618164  ...      0.508730  208000 -0.007160
2   5380  2021-09-17  207240.556641  ...      0.508730  209000  0.004808
3   5380  2021-09-23  206701.343750  ...      0.508730  208500 -0.002392
4   5380  2021-09-24  206449.753906  ...      0.508730  207000 -0.007194
5   5380  2021-09-27  206681.316406  ...      0.508730  204000 -0.014493
6   5380  2021-09-28  205415.191406  ...      0.508730  201500 -0.012255
7   5380  2021-09-29  204147.993164  ...      0.508730  201500  0.000000
8   5380  2021-09-30  203129.835938  ...      0.508730  200000 -0.007444
9   5380  2021-10-01  202319.210938  ...      0.508730  193500 -0.032500
0  68270  2021-09-15  260272.124023  ...      0.508730  272500  0.036122
1  68270  2021-09-16  266626.185547  ...      0.508730  267000 -0.020183
2  68270  2021-09-17  267362.367188  ...      0.508730  275500  0.031835
3  68270  2021-09-23  271181.423828  ...      0.508730  284500  0.032668
4  68270  2021-09-24  279808.167969  ...      0.508730  274500 -0.035149
5  68270  2021-09-27  272324.314453  ...      0.508730  267500 -0.025501
6  68270  2021-09-28  267896.691406  ...      0.508730  263500 -0.014953
7  68270  2021-09-29  261424.762695  ...      0.508730  261000 -0.009488
8  68270  2021-09-30  256538.727539  ...      0.508730  259500 -0.005747
9  68270  2021-10-01  257239.620117  ...      0.508730  248000 -0.044316

[50 rows x 15 columns]

In [8]:
# ud 테이블
samsung_ud = pd.read_csv(path + '삼성전자/samsung_table_ud.csv')
lg_ud = pd.read_csv(path + 'lg화학/lg_table_ud.csv')
sk_ud = pd.read_csv(path + 'sk하이닉스/hy_table_ud.csv')
hun_ud = pd.read_csv(path + '현대차/hun_table_ud.csv')
cell_ud = pd.read_csv(path + '셀트리온/cel_table_ud.csv')

total_ud = pd.concat([samsung_ud,lg_ud,sk_ud,hun_ud,cell_ud])
total_ud

    code        date       lstm  ...  hk_youtube  suka_youtube  change
0   5930  2021-09-15   75550.37  ...           1             1       1
1   5930  2021-09-16       1.00  ...           1             1      -1
2   5930  2021-09-17       1.00  ...           1             1       1
3   5930  2021-09-23       1.00  ...           1             1       0
4   5930  2021-09-24       1.00  ...          -1             1       0
5   5930  2021-09-27      -1.00  ...          -1             1       1
6   5930  2021-09-28       1.00  ...          -1             1      -1
7   5930  2021-09-29       1.00  ...          -1             1      -1
8   5930  2021-09-30      -1.00  ...           1             1       0
9   5930  2021-10-01      -1.00  ...           1             1      -1
0  51910  2021-09-15  733916.57  ...           0             1      -1
1  51910  2021-09-16      -1.00  ...           1             1       0
2  51910  2021-09-17      -1.00  ...           1             1      -1
3  51910  2021-09-23      -1.00  ...           1             1       1
4  51910  2021-09-24      -1.00  ...           1             1       0
5  51910  2021-09-27       1.00  ...          -1             1       1
6  51910  2021-09-28       1.00  ...          -1             1       1
7  51910  2021-09-29       1.00  ...           1             1      -1
8  51910  2021-09-30       1.00  ...           1             1       1
9  51910  2021-10-01       1.00  ...           1             1      -1
0    660  2021-09-15  107611.11  ...           0             1       0
1    660  2021-09-16      -1.00  ...          -1             1      -1
2    660  2021-09-17       1.00  ...           1             1       1
3    660  2021-09-23      -1.00  ...          -1             1      -1
4    660  2021-09-24      -1.00  ...          -1             1      -1
5    660  2021-09-27       1.00  ...          -1             1       0
6    660  2021-09-28      -1.00  ...          -1             1      -1
7    660  2021-09-29       1.00  ...          -1             1      -1
8    660  2021-09-30      -1.00  ...           0             1       1
9    660  2021-10-01      -1.00  ...           1             1      -1
0   5380  2021-09-15  208400.87  ...           1             1       0
1   5380  2021-09-16      -1.00  ...          -1             1      -1
2   5380  2021-09-17      -1.00  ...          -1             1       0
3   5380  2021-09-23      -1.00  ...           1             1       0
4   5380  2021-09-24      -1.00  ...           1             1      -1
5   5380  2021-09-27       1.00  ...          -1             1      -1
6   5380  2021-09-28      -1.00  ...          -1             1      -1
7   5380  2021-09-29      -1.00  ...          -1             1       0
8   5380  2021-09-30      -1.00  ...          -1             1      -1
9   5380  2021-10-01      -1.00  ...           1             1      -1
0  68270  2021-09-15  260272.12  ...           0             1       1
1  68270  2021-09-16       1.00  ...          -1             1      -1
2  68270  2021-09-17       1.00  ...          -1             1       1
3  68270  2021-09-23       1.00  ...          -1             1       1
4  68270  2021-09-24       1.00  ...          -1             1      -1
5  68270  2021-09-27      -1.00  ...          -1             1      -1
6  68270  2021-09-28      -1.00  ...          -1             1      -1
7  68270  2021-09-29      -1.00  ...          -1             1      -1
8  68270  2021-09-30      -1.00  ...          -1             1      -1
9  68270  2021-10-01       1.00  ...          -1             1      -1

[50 rows x 14 columns]

In [10]:
total.to_csv('./total.csv', index=False)
total_ud.to_csv('./total_ud.csv', index=False)